### ISSUE TITLE
Switch to using OIDC for deployment

### ISSUE THREAD

**Issue by simoneb** [nearform/optic-release-automation-app#277]
We currently use long lived credentials for deployment, we should use OIDC instead

**Comment by simoneb** [comment]
@heidermassu this would be a good playground to test that we can use the other work you're doing to set up OIDC. This app is currently being deployed without OIDC, so once that work is ready we can test it against this repo to switch to using OIDC.

/cc @andreacfm

**Comment by simoneb** [comment]
This activity was reopened because the first attempt didn't go as planned. The project where the cloud run service was deployed was compromised to the extent that it wasn't easily possible to recover it, and I decided to delete it.

The cloud run service is now running under a different project.

We should:

- create a new project from scratch
- set it up with OIDC
- deploy the service
- use a DNS name to point to it to avoid the issue we had the last time
- change the github action to point to this url

For the provisioning of the service account, given the bad experience we had the last time, I would recommend that we do it manually this time.

**Comment by heidermassu** [comment]
Simone, Related to the service account provision the automation to create it there was not responsible for deletion or any issue occured! This one works well in a project that was created from scratch. The issue was in this project even without deleting the cloud run I was facing a problem creating a new cloud run service because of an account that does not exist anymore and was saying that exists.  Heider Leandro Massu HengstmannSenior DevOps Engineer | +1 530 616 8129 ***@***.***—Twitter | Linkedin | Facebook | YouTube  From: Simone BusoliSent: terça-feira, 27 de junho de 2023 05:29To: nearform/optic-release-automation-appCc: Heider Leandro Massu Hengstmann; State changeSubject: Re: [nearform/optic-release-automation-app] Switch to using OIDC for deployment (Issue #277) This activity was reopened because the first attempt didn't go as planned. The project where the cloud run service was deployed was compromised to the extent that it wasn't easily possible to recover it, and I decided to delete it.The cloud run service is now running under a different project.We should:create a new project from scratchset it up with OIDCdeploy the serviceuse a DNS name to point to it to avoid the issue we had the last timechange the github action to point to this urlFor the provisioning of the service account, given the bad experience we had the last time, I would recommend that we do it manually this time.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>

**Comment by andreacfm** [comment]
Some questions:
* any suggestion for the new project name?
* what domain are we going to use and who is managing the dns?

**Comment by simoneb** [comment]
@andreacfm

- I have deleted the previous project, so I'd ask IT to create a new one with the same name, which should be possible since the previous one is now deleted. For consistency, I'd stick to the same name as the repo, meaning optic-release-automation-app
- For the DNS, I would use the same name: optic-release-automation-app.nearform.com, and once we have the cloud run service running we should:
  1. ask IT to set it up on that cloud run service
  2. update the action to reflect this new url, here specifically: https://github.com/nearform-actions/optic-release-automation-action/blob/main/action.yml#L42

**Comment by simoneb** [comment]
@andreacfm when we're happy with the outcome of this, please let's close this issue
